# Where things are
source              : .
destination         : ./_site
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
collections:
  posts:
    output          : true

# Handling Reading
safe                : false
include             : []
exclude             : [".git", ".gitignore", ".vscode", "Gemfile", "Gemfile.lock", "LICENSE"]
keep_files          : ["favicon.png",  "site.webmanifest", "assets/favicons", "assets/images", "assets/lib"]
encoding            : "utf-8"
markdown_ext        : "md"
strict_front_matter : false

# Filtering Content
show_drafts         : null
limit_posts         : 0
future              : false
unpublished         : false

# Conversion
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

# Serving
detach              : false
port                : 4000
host                : 127.0.0.1
baseurl             : "" # does not include hostname
show_dir_listing    : false

# Outputting
permalink           : :year-:month-:day/:title:output_ext
paginate_path       : /page:num
timezone            : null

quiet               : false
verbose             : false
defaults            : []

liquid:
  error_mode        : warn
  strict_filters    : false
  strict_variables  : false

# Scss / CSS compression
sass:
    style: compressed
    sass_dir: assets/css

# Markdown Processors
rdiscount:
  extensions        : []

redcarpet:
  extensions        : []

kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : 1..6
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false